# Compose a postgres database together with the extension pgvector
services:
  db:
    hostname: db
    image: ankane/pgvector
    ports:
     - 9876:9876
    restart: always
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpwd
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
