version: '3.8'

services:
  preprocess:
    container_name: preprocess
    build:
      context: ./preprocess
      dockerfile: Dockerfile
    volumes:
      - ./preprocess:/home/app
      - ./data:/data
    command: python /home/app/preprocess.py
    healthcheck:
      test: ["CMD", "test", "-f", "/data/complete.txt"]
      interval: 1m
      timeout: 10s
      retries: 999999999

  postgres-database:
    hostname: postgres-database
    container_name: semantic_tag_db
    image: ankane/pgvector
    ports:
     - 9876:5432
    restart: always
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/csv
      - semantic_tag_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 25s
      timeout: 10s
      retries: 5
    depends_on:
      preprocess:
        condition: service_healthy

  api:
    hostname: api
    container_name: semantic_tag_api
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/home/app
    ports:
      - 8008:5000    
    depends_on:
      postgres-database:
        condition: service_healthy

  web:
    container_name: semantic_tag_web
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/public:/home/app/public
      - ./frontend/src:/home/app/src
    ports:
      - 6868:3000    
    depends_on:
      - api

volumes:
  semantic_tag_db:
