version: '3.8'

services:
  postgres-database:
    hostname: postgres-database
    container_name: semantic_tag_db
    image: ankane/pgvector
    ports:
     - 9876:5432
    restart: always
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/csv
      - semantic_tag_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 25s
      timeout: 10s
      retries: 5

  app:
    container_name: semantic_tag_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/app
    ports:
      - 8008:5000    
    depends_on:
      postgres-database:
        condition: service_healthy

volumes:
  semantic_tag_db:
